package uk.ac.ed.inf;

import java.util.*;

/**
 * this class is used when information related to an order is needed to be stored and processed
 *
 */
public class Order {

    /**
     * this is the order number of the order
     */
    public String orderNO;
    /**
     * this is the location of the delivery destination
     */
    public String deliverTo;
    /**
     * this is a collection of all the items' names included in this order
     */
    public ArrayList<String> itemList;

    /**
     * this is a constructor of the Order class
     *
     * @param orderNO this is the order number of the order
     * @param deliverTo this is the delivery location of the order
     * @param itemList this is the list of items' names for the items in this order
     */
    public Order(String orderNO, String deliverTo, ArrayList<String> itemList) {
        this.orderNO = orderNO;
        this.deliverTo = deliverTo;
        this.itemList = itemList;
    }


    /**
     * this method calculate the total amount of money made by doing this order which includes
     * a fixed delivery charge 50 pence
     *
     * @param itemsPriceMap this is the (item name, item price) HashMap generated by method in Menus class
     * @return the total price of this order included the 50p delivery charge
     */
    public int getOrderCost(HashMap<String, Integer> itemsPriceMap){
        int PRICE = 0;
        try{
            for(String item : itemList){
                PRICE += itemsPriceMap.get(item);
            }
        } catch(ArrayIndexOutOfBoundsException|NullPointerException e){
            System.err.println("The item isn't found in the menu.");
            System.exit(1);
        }catch (Exception e){
            System.exit(1);
        }
        int DELIVERY_COST = 50;
        return PRICE + DELIVERY_COST;
    }

    /**
     * this method summarize all the shops need to be visited by the drone to pick up all the items
     * required in the order.
     *
     * @param itemsLocationMap this is the (item name, item shop) HashMap map generated by method in Menus class
     * @return a set of all the shops the drone needs to visit
     */
    public List<String> getOrderShops(HashMap<String, String> itemsLocationMap){
        Set<String> shopLocations = new HashSet<>();
        for(String item : itemList){
            try{
                String location = itemsLocationMap.get(item);
                shopLocations.add(location);
            } catch (NullPointerException e){
                System.err.println("Item is not found in the menu");
                System.exit(1);
            }catch (Exception e){
                System.exit(1);
            }
        }
        return new ArrayList<>(shopLocations);
    }

}
